---
title: "About the RSU"
---

The BFI Research and Statistics Unit produces research, data and market intelligence on the UK film industry and other screen sectors. 

Our activities are supported by the BFI National Lottery Research and Statistics Fund, 

The objectives of the fund are to:

* increase and improve the quality and impact of evidence underpinning decisions on the future of the sector – their culture, practice and economic and policy needs;
* provide users from industry, government and academia with instant access to statistics, analysis and research resources;
* address a series of key research priorities for the screen sectors;
* foster strategic collaboration between public policy-makers, industry, academia and wider screen-sector stakeholders;
* distribute findings so they are available for stakeholders and the public.

See the [Industry data and insights](https://www.bfi.org.uk/industry-data-insights) page on the [BFI website](https://www.bfi.org.uk/) for further details.